version: '3.5'

services:
  application:
    build: .
    image: app
    command: sh -c "yarn sequelize db:migrate && yarn sequelize db:seed:all && yarn dev"
    ports:
      - 3250:3250
    environment:
      DATABASE_URI: mysql://albacross:albacross@mysql:3306/albacross
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - albacross
  mysql:
    image: mysql:8.0.15
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: albacross
      MYSQL_USER: albacross
      MYSQL_PASSWORD: albacross
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - albacross

volumes:
  mysql-volume:

networks:
  albacross:
    name: albacross-public-network
